#include<stdio.h>
#include<string.h>
#include<iostream>
using namespace std;

int main()
{
	int t;
	scanf("%d",&t);
	while(t--)
	{
		char word[101];
		scanf("%s",word);
		int count=0;
		for(int i = 0 ; i <strlen(word);i++)
		{
			if(word[i]=='a'||word[i]=='A')
			{
				count+=2;
				continue;
			}
			if(word[i]=='b'||word[i]=='B')
			{
				count+=4;
				continue;
			}
			if(word[i]=='c'||word[i]=='C')
			{
				count+=6;
				continue;
			}
			if(word[i]=='d'||word[i]=='D')
			{
				count+=3;
				continue;
			}
			if(word[i]=='e'||word[i]=='E')
			{
				count+=6;
				continue;
			}
			if(word[i]=='f'||word[i]=='F')
			{
				count+=9;
				continue;
			}
			if(word[i]=='g'||word[i]=='G')
			{
				count+=4;
				continue;
			}
			if(word[i]=='h'||word[i]=='H')
			{
				count+=8;
				continue;
			}
			if(word[i]=='i'||word[i]=='I')
			{
				count+=12;
				continue;
			}
			if(word[i]=='j'||word[i]=='J')
			{
				count+=5;
				continue;
			}
			if(word[i]=='k'||word[i]=='K')
			{
				count+=10;
				continue;
			}
			if(word[i]=='l'||word[i]=='L')
			{
				count+=15;
				continue;
			}
			if(word[i]=='m'||word[i]=='M')
			{
				count+=6;
				continue;
			}
			if(word[i]=='n'||word[i]=='N')
			{
				count+=12;
				continue;
			}
			if(word[i]=='o'||word[i]=='O')
			{
				count+=18;
				continue;
			}
			if(word[i]=='p'||word[i]=='P')
			{
				count+=7;
				continue;
			}
			if(word[i]=='q'||word[i]=='Q')
			{
				count+=14;
				continue;
			}
			if(word[i]=='r'||word[i]=='R')
			{
				count+=21;
				continue;
			}
			if(word[i]=='s'||word[i]=='S')
			{
				count+=28;
				continue;
			}
			if(word[i]=='t'||word[i]=='T')
			{
				count+=8;
				continue;
			}
			if(word[i]=='u'||word[i]=='U')
			{
				count+=16;
				continue;
			}
			if(word[i]=='v'||word[i]=='V')
			{
				count+=24;
				continue;
			}
			if(word[i]=='w'||word[i]=='W')
			{
				count+=9;
				continue;
			}
			if(word[i]=='x'||word[i]=='X')
			{
				count+=18;
				continue;
			}
			if(word[i]=='y'||word[i]=='Y')
			{
				count+=27;
				continue;
			}
			if(word[i]=='z'||word[i]=='Z')
			{
				count+=36;
				continue;
			}
																																																																																	
        
		}
		printf("%d\n",count);
	}
}